
[[props]]
name = "start"
id = 0
type = "BOOL"
writeable = true

[[props]]
name = "stop"
id = 1
type = "BOOL"
writeable = true

[[props]]
name = "status"
id = 2
type = "U32"
readable = true

[[props]]
name = "telem_data"
id = 10
type = "ARR"
# float(4)
# imu(r, p, y, gx, gy, gz) [24]
# lidar [4]
# esc [4]
size = 32
readable = true

[[props]]
# a stream of this property will read back all data
# the stream will stop on its own when all data has been
# read
name = "telem_cap"
id = 11
type = "ARR"
# bytes
size = 64
readable = true

[[props]]
# start telemetry capture
name = "telem_cap_start"
id = 12
type = "BOOL"
size = 1
writeable = true

[[props]]
# stop telemetry capture
name = "telem_cap_stop"
id = 13
type = "BOOL"
size = 1
writeable = true

[[props]]
name = "battery_v"
id = 18
type = "FLOAT"
size = 4
readable = true

[[props]]
name = "timestamp_ms"
id = 19
type = "U32"
size = 4
readable = true

[[props]]
# remote board reset
name = "reset_system"
id = 30
type = "BOOL"
size = 1
writeable = true

[[props]]
name = "servo_positions"
id = 40
type = "ARR"
# degress float(4)
# servo[4] * 4
size = 16
readable = true
writeable = true

[[props]]
# delta from current
name = "target_position"
id = 41
type = "ARR"
# p(x,y,z)
size = 12
writeable = true
readable = true

[[props]]
name = "raw_lidar"
id = 50
type = "U32"
size = 4
readable = true

[[props]]
name = "raw_imu"
id = 51
type = "ARR"
# 10 floats
size = 40
readable = true

[[props]]
name = "imu"
id = 52
type = "ARR"
# 6 floats
size = 24
readable = true

[[props]]
name = "esc_pwm"
id = 53
type = "FLOAT"
size = 1
readable = true
writeable = true

[[props]]
name = "k_matrix"
id = 54
type = "ARR"
size = 180
writeable = true

[[props]]
name = "z_lim_spinup"
id = 55
type = "FLOAT"
size = 4
writeable = true

[[props]]
name = "z_lim_normal"
id = 56
type = "FLOAT"
size = 4
writeable = true

[[props]]
name = "max_zint"
id = 57
type = "FLOAT"
size = 4
writeable = true

[[props]]
name = "max_esc_out"
id = 58
type = "FLOAT"
size = 4
writeable = true
