
[[props]]
name = "start"
id = 0
type = "BOOL"
writeable = true

[[props]]
name = "stop"
id = 1
type = "BOOL"
writeable = true

[[props]]
name = "status"
id = 2
type = "U32"
readable = true

[[props]]
name = "telem_data"
id = 10
type = "ARR"
# float(4)
# p(x,y,z) [12]
# v(x,y,z) [12]
# a(x,y,z) [12]
# o(r,p,y) [12]
# alt [4]
size = 52
readable = true

[[props]]
# a stream of this property will read back all data
# the stream will stop on its own when all data has been
# read
name = "telem_cap"
id = 11
type = "ARR"
# bytes
size = 64
readable = true

[[props]]
# start telemetry capture
name = "telem_cap_start"
id = 12
type = "BOOL"
size = 1
writeable = true

[[props]]
# stop telemetry capture
name = "telem_cap_stop"
id = 13
type = "BOOL"
size = 1
writeable = true

[[props]]
name = "battery_v"
id = 18
type = "FLOAT"
size = 4
readable = true

[[props]]
name = "timestamp_ms"
id = 19
type = "U32"
size = 4
readable = true

[[props]]
# telemetry values are read after filtering if enabled
name = "telem_filter_en"
id = 20
type = "BOOL"
size = 4
readable = true

[[props]]
# remote board reset
name = "reset_system"
id = 30
type = "BOOL"
size = 1
writeable = true

[[props]]
# reset only control flight systems and control
# (e.g. soft soft reset between tests without power cycling, zero out values etv.)
name = "reset_controls"
id = 31
type = "BOOL"
size = 1
writeable = true

[[props]]
name = "servo_positions"
id = 40
type = "ARR"
# degress float(4)
# servo[4] * 4
size = 16
readable = true
writeable = true

[[props]]
# delta from current
name = "target_position"
id = 41
type = "ARR"
# p(x,y,z)
size = 12
writeable = true
readable = true

[[props]]
name = "param_bounds"
id = 42
type = "ARR"
# max_val[4*3]
# max_accel[4*3]
# max_angular[4*3]
size = 36
writeable = true
readable = true


